# Ruff configuration for MuJoCo MCP
target-version = "py310"
line-length = 100

[lint]
# Enable specific rule sets
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "N",   # pep8-naming
    "UP",  # pyupgrade
    "YTT", # flake8-2020
    "S",   # flake8-bandit
    "BLE", # flake8-blind-except
    "B",   # flake8-bugbear
    "A",   # flake8-builtins
    "C4",  # flake8-comprehensions
    "T10", # flake8-debugger
    "EXE", # flake8-executable
    "ISC", # flake8-implicit-str-concat
    "ICN", # flake8-import-conventions
    "G",   # flake8-logging-format
    "PIE", # flake8-pie
    "T20", # flake8-print
    "PT",  # flake8-pytest-style
    "Q",   # flake8-quotes
    "RSE", # flake8-raise
    "RET", # flake8-return
    "SLF", # flake8-self
    "SIM", # flake8-simplify
    "TID", # flake8-tidy-imports
    "TCH", # flake8-type-checking
    "ARG", # flake8-unused-arguments
    "PTH", # flake8-use-pathlib
    "ERA", # eradicate
    "PD",  # pandas-vet
    "PGH", # pygrep-hooks
    "PL",  # pylint
    "TRY", # tryceratops
    "FLY", # flynt
    "NPY", # numpy
    "RUF", # ruff-specific rules
]

# Selectively ignore rules that need gradual fixing
ignore = [
    # Import and unused variable issues (will be fixed gradually)
    "F841",    # Local variable assigned but never used
    
    # Code quality issues - these should be enabled for better code quality
    # "E722",    # Bare except - should be fixed
    # "W291",    # Trailing whitespace - handled by pre-commit
    # "W292",    # No newline at end of file - handled by pre-commit  
    # "W293",    # Blank line contains whitespace - handled by pre-commit
    # "E501",    # Line too long - handled by black/ruff format
    
    # Type annotation modernization (can be done later)
    "UP006",   # Use `dict` instead of `Dict` for type annotation
    "UP007",   # Use `X | Y` for type annotations
    "UP035",   # Use modern typing syntax
    "UP038",   # Use `X | Y` in `isinstance` call
    
    # Code style (can be standardized later)
    "Q000",    # Single quotes vs double quotes
    "I001",    # Import block is un-sorted
    "RUF010",  # Use explicit conversion flag
    "RUF013",  # PEP 484 prohibits implicit `Optional`
    "RUF022",  # `__all__` is not sorted
    "RUF003",  # Comment contains ambiguous characters
    "RUF001",  # String contains ambiguous unicode
    "RUF002",  # Docstring contains ambiguous unicode
    "RUF015",  # Prefer next(iter()) over single element slice
    
    # Print statements (keep for scripts and CLI)
    "T201",    # Print statements found
    
    # String formatting and concatenation - enable these for better code
    # "ISC003",  # Explicitly concatenated string should be implicitly concatenated
    # "G003",    # Logging statement uses `+`
    
    # Code comments and cleanup - enable this for cleaner code
    # "ERA001",  # Found commented-out code
    
    # Exception handling patterns - enable these for better error handling
    # "TRY301",  # Abstract `raise` to an inner function
    # "TRY400",  # Use `logging.exception` instead of `logging.error`
    
    # Return statement optimization - enable for cleaner code
    # "RET504",  # Unnecessary assignment before `return` statement
    
    # Path handling modernization (can be done later)
    "PTH118",  # `os.path.join()` should be replaced by `Path` with `/` operator
    "PTH120",  # `os.path.dirname()` should be replaced by `Path.parent`
    "PTH109",  # `os.getcwd()` should be replaced by `Path.cwd()`
    "PTH110",  # `os.path.exists()` should be replaced by `Path.exists()`
    "PTH100",  # `os.path.abspath()` should be replaced by `Path.resolve()`
    
    # Subprocess security (acceptable for this project)
    "S603",    # `subprocess` call: check for execution of untrusted input
    "PLW1510", # `subprocess.run` without explicit `check` argument
    "S607",    # Starting a process with a partial executable path
    
    # Executable and shebang issues
    "EXE001",  # Shebang is present but file is not executable
    
    # Complex function issues (will refactor later)
    "PLR0911", # Too many return statements
    "PLR0913", # Too many arguments to function call
    "PLR0912", # Too many branches
    "PLR0915", # Too many statements
    "PLR2004", # Magic value used in comparison
    "PLR0402", # Use `from mcp import types` in lieu of alias
    
    # Global variables (temporary during refactoring)
    "PLW0603", # Using the global statement
    
    # Exception handling (will improve later)
    "BLE001",  # Do not catch blind exception
    "TRY003",  # Avoid specifying long messages outside the exception class
    "TRY300",  # Consider moving this statement to an `else` block
    
    # Private member access (legacy code)
    "SLF001",  # Private member accessed
    
    # Security (not critical for this project)
    "S101",    # Use of assert
    "S311",    # Standard pseudo-random generators
    
    # Style preferences
    "SIM108",  # Use ternary operator
    "SIM102",  # Use a single if-statement
    "SIM117",  # Combine multiple isinstance checks
    "RET505",  # Unnecessary `else` after `return`
    "RET506",  # Unnecessary `else` after `raise`
    "RET507",  # Unnecessary `else` after `continue`
    "RET508",  # Unnecessary `else` after `break`
    "EM101",   # Exception must not use a string literal
    "EM102",   # Exception must not use an f-string literal
    "G004",    # Logging statement uses f-string
    "PD901",   # Avoid using the generic variable name `df`
]

# Exclude specific files/directories
exclude = [
    ".git",
    "__pycache__",
    ".pytest_cache",
    ".ruff_cache",
    "build",
    "dist",
    "*.egg-info",
    ".venv",
    "test_envs",
    "test_install",
    # Exclude legacy/experimental files during development
    "src/mujoco_mcp/server_old.py",
    "src/mujoco_mcp/server_new.py", 
    "src/mujoco_mcp/server_v0_1_1.py",
    "src/mujoco_mcp/simple_server.py",
    "src/mujoco_mcp/enhanced_auth_manager.py",
    "src/mujoco_mcp/menagerie_loader.py",
    "src/mujoco_mcp/remote_server.py",
    "src/mujoco_mcp/video_recorder.py",
    "tests/test_*.py",  # Exclude tests from some rules temporarily
]

[lint.per-file-ignores]
# Test files can have some relaxed rules
"tests/**/*.py" = [
    "S101",    # Use of assert
    "PLR2004", # Magic values in tests are OK
    "ARG001",  # Unused function arguments in tests
    "F401",    # Unused imports in tests
]

# Scripts can have relaxed rules
"scripts/**/*.py" = [
    "T201",    # Print statements are OK in scripts
    "S101",    # Assert is OK in scripts
    "PLR2004", # Magic values are OK in scripts
]

# Main module files
"src/mujoco_mcp/__main__.py" = [
    "T201",    # Print statements are OK in CLI
]

# MCP server module - core functionality
"src/mujoco_mcp/mcp_server.py" = [
    "F401",    # Allow unused imports temporarily
]

[lint.isort]
known-first-party = ["mujoco_mcp"]
force-single-line = true
force-sort-within-sections = true

[lint.flake8-quotes]
inline-quotes = "double"
multiline-quotes = "double"

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"