name: MCP Compliance Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run weekly on Sundays at 6 AM UTC
    - cron: '0 6 * * 0'

jobs:
  mcp-compliance:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "18"
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        
    - name: Install MCP Inspector
      run: |
        npm install -g @modelcontextprotocol/inspector
        
    - name: Test MCP Protocol Compliance
      run: |
        python test_mcp_compliance.py
        
    - name: Upload compliance report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: mcp-compliance-report
        path: mcp_compliance_report.json
        
    - name: Test MCP Inspector Integration
      run: |
        timeout 30 npx @modelcontextprotocol/inspector python -m mujoco_mcp || echo "Timeout expected for non-interactive test"