name: Performance Benchmark

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run nightly at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  benchmark:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install psutil
        pip install -e .
        
    - name: Run performance benchmarks
      run: |
        python test_performance_benchmark.py
        
    - name: Upload benchmark results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: performance-report-${{ github.sha }}
        path: performance_benchmark_report.json
        
    - name: Check performance regression
      run: |
        python -c "
        import json
        with open('performance_benchmark_report.json') as f:
            results = json.load(f)
        
        # Check if performance targets are met
        startup_time = results.get('startup_time', {}).get('mean', 0)
        if startup_time > 5.0:
            print(f'❌ Performance regression: startup time {startup_time:.2f}s > 5.0s')
            exit(1)
        else:
            print(f'✅ Performance OK: startup time {startup_time:.2f}s')
        "