name: Performance Benchmark

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run nightly at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  benchmark:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install psutil
        pip install -e .
        
    - name: Run performance benchmarks
      run: |
        python test_performance_benchmark.py
        
    - name: Upload benchmark results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: performance-report-${{ github.sha }}
        path: performance_benchmark_report.json
        
    - name: Check performance regression
      run: |
        python -c "
        import json
        import os
        
        if os.path.exists('performance_benchmark_report.json'):
            with open('performance_benchmark_report.json') as f:
                results = json.load(f)
            
            # Check overall success rate
            summary = results.get('summary', {})
            success_rate = summary.get('success_rate', 0.0)
            total_time = summary.get('total_execution_time', 0.0)
            
            print(f'📊 Benchmark Results:')
            print(f'   Success Rate: {success_rate:.1%}')
            print(f'   Total Time: {total_time:.2f}s')
            
            # Performance thresholds
            if success_rate < 0.8:  # 80% success rate
                print(f'❌ Performance regression: success rate {success_rate:.1%} < 80%')
                exit(1)
            elif total_time > 60.0:  # 60 seconds max
                print(f'❌ Performance regression: total time {total_time:.2f}s > 60s')
                exit(1)
            else:
                print(f'✅ Performance targets met')
        else:
            print('⚠️ No benchmark results found - skipping regression check')
        "